apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:eks:us-east-1:210893161398:cluster/eks-repo
      username: eks-repo
      groups:
        - system:masters
