apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::210893161398:user/terra1
      username: admin-user1
      groups:
        - system:masters
